server:
  build: images/server
  volumes:
    - ./images/server/app/:/var/www/html
  ports:
    - "8123:80"
  links:
    - db
  environment:
    APP_ENV: local
    APP_DEBUG: 'true'
    APP_KEY: SomeRandomKey!!!
    APP_LOCALE: en
    APP_FALLBACK_LOCALE: en
    DB_CONNECTION: mysql
    DB_HOST: db
    DB_DATABASE: lumen
    DB_USERNAME: lumen
    DB_PASSWORD: secret
db:
  image: mysql
  ports:
    - "3306:3306"
  volumes: 
    - ./dump:/docker-entrypoint-initdb.d
    - persistent:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: lumen
    MYSQL_USER: lumen
    MYSQL_PASSWORD: secret
frontend:
  build: images/frontend
  ports:
    - "8080:80"
  working_dir: /var/www/html/